name: wflow

channels:
  - conda-forge
  - defaults
  - conda-forge/label/dev

dependencies:
  - python=2.7
  - numpy>=1.12
  - gdal>=2.2
  - rasterio>=1.0a12
  - netcdf4>=1.3
  - pyproj>=1.9
  - thrift>=0.11
  - pyinstaller>=3.3
  - versioneer>=0.18
  - pywin32>=221
